steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build'
  - '-f'
  - 'Dockerfile.simple'
  - '-t'
  - 'gcr.io/$PROJECT_ID/lyobackend-phase3'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'push'
  - 'gcr.io/$PROJECT_ID/lyobackend-phase3'
images:
- 'gcr.io/$PROJECT_ID/lyobackend-phase3'
