"""Validated visual teaching tools shared by native and web classrooms.

Visuals are instructional representations, not decoration and never grading
signals. Real images are resolved server-side from Wikimedia Commons so model
output cannot inject arbitrary media URLs. Every visual keeps an equivalent
text description for accessibility and degraded/offline clients.
"""

import ast
import asyncio
import html
import math
import re
from typing import Any, Literal
from urllib.parse import urlparse
from uuid import uuid4

import httpx
from pydantic import BaseModel, ConfigDict, Field, model_validator


class VisualItem(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True, allow_inf_nan=False)
    label: str = Field(min_length=1, max_length=80)
    detail: str = Field(min_length=1, max_length=240)
    # Optional geometry. Timelines/process flows ignore it; number lines use
    # position, and annotated images use normalized x/y coordinates.
    position: float | None = Field(default=None, ge=-1000000, le=1000000)
    x: float | None = Field(default=None, ge=0, le=1)
    y: float | None = Field(default=None, ge=0, le=1)


class VisualParameter(BaseModel):
    model_config = ConfigDict(extra="forbid", allow_inf_nan=False)
    name: str = Field(pattern=r"^[a-wyzA-WYZ][a-zA-Z0-9_]{0,12}$")
    min: float = Field(ge=-10000, le=10000)
    max: float = Field(ge=-10000, le=10000)
    initial: float
    step: float = Field(default=1, gt=0, le=10000)

    @model_validator(mode="after")
    def bounded(self):
        if not self.min < self.max or not self.min <= self.initial <= self.max:
            raise ValueError("Parameter needs an ordered range and a value inside it")
        return self


_TRUSTED_IMAGE_HOSTS = {"upload.wikimedia.org", "commons.wikimedia.org"}
_IMAGE_CACHE: dict[str, tuple[str, str, str]] = {}


def _trusted_https(url: str | None) -> bool:
    if not url:
        return False
    parsed = urlparse(url)
    return parsed.scheme == "https" and parsed.hostname in _TRUSTED_IMAGE_HOSTS


class TeachingVisual(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True, allow_inf_nan=False)
    # visual_id is generated by the server when omitted and persists with the
    # saved turn so a later scene can reference the same teaching object.
    visual_id: str = Field(default_factory=lambda: str(uuid4()), min_length=8, max_length=64)
    kind: Literal[
        "fraction_bar", "comparison", "sequence", "graph",
        "process_flow", "timeline", "number_line", "annotated_image",
    ]
    title: str = Field(min_length=3, max_length=100)
    caption: str = Field(min_length=10, max_length=350)
    # Equivalent textual account for accessibility and older/degraded clients.
    description: str = Field(min_length=10, max_length=600)
    parts: int = Field(default=10, ge=2, le=20)
    whole: float = Field(default=1, gt=0, le=1000000)
    unit: str = Field(default="", max_length=40)
    value: int = Field(default=0, ge=0, le=20)
    entries: list[VisualItem] = Field(default_factory=list, max_length=8)
    expression: str = Field(default="", max_length=150)
    params: list[VisualParameter] = Field(default_factory=list, max_length=3)
    x_min: float = Field(default=-5, ge=-1000000, le=1000000)
    x_max: float = Field(default=5, ge=-1000000, le=1000000)
    y_min: float = Field(default=-10, ge=-1000000, le=1000000)
    y_max: float = Field(default=10, ge=-1000000, le=1000000)
    # For annotated_image the model supplies only image_query + annotation
    # entries. These three fields are populated by the trusted resolver.
    image_query: str = Field(default="", max_length=140)
    image_url: str | None = Field(default=None, max_length=1200)
    source_url: str | None = Field(default=None, max_length=1200)
    attribution: str | None = Field(default=None, max_length=240)

    @model_validator(mode="after")
    def useful_visual(self):
        if self.kind == "fraction_bar" and self.value > self.parts:
            raise ValueError("Shaded parts cannot exceed the whole")

        if self.kind in ("comparison", "sequence", "process_flow", "timeline"):
            if len(self.entries) < 2 or self.value >= len(self.entries):
                raise ValueError("Provide at least two real examples or steps")

        if self.kind == "number_line":
            if len(self.entries) < 2 or self.value >= len(self.entries) or self.x_min >= self.x_max:
                raise ValueError("A number line needs ordered bounds and at least two markers")
            if any(item.position is None or not self.x_min <= item.position <= self.x_max
                   for item in self.entries):
                raise ValueError("Every number-line marker needs a position inside the bounds")

        if self.kind == "annotated_image":
            if not self.image_query:
                raise ValueError("An annotated image needs a concrete image query")
            for item in self.entries:
                if (item.x is None) != (item.y is None):
                    raise ValueError("Image annotation coordinates need both x and y")
            # Model-supplied arbitrary URLs are rejected. The resolver below
            # only ever writes Wikimedia hosts.
            if self.image_url and not _trusted_https(self.image_url):
                raise ValueError("Image URL must come from the trusted resolver")
            if self.source_url and not _trusted_https(self.source_url):
                raise ValueError("Image source must come from the trusted resolver")

        if self.kind == "graph":
            if not self.expression or not self.params or self.x_min >= self.x_max or self.y_min >= self.y_max:
                raise ValueError("A graph needs an expression, parameters and ordered bounds")
            names = {p.name for p in self.params}
            functions = {"sin", "cos", "tan", "exp", "log", "ln", "sqrt", "abs"}
            if len(names) != len(self.params) or names & (functions | {"x", "pi", "e"}):
                raise ValueError("Graph parameters must be distinct")
            tokens = set(re.findall(r"[a-zA-Z][a-zA-Z0-9_]*", self.expression))
            allowed = names | {"x", "pi", "e"} | functions
            if tokens - allowed or re.search(r"[^a-zA-Z0-9_+*/^().\s-]", self.expression):
                raise ValueError("Only supported mathematical expressions are allowed")
            try:
                tree = ast.parse(self.expression.replace("^", "**"), mode="eval")
            except SyntaxError as exc:
                raise ValueError("Provide a complete mathematical expression") from exc
            permitted = (ast.Expression, ast.BinOp, ast.UnaryOp, ast.Add, ast.Sub, ast.Mult,
                         ast.Div, ast.Pow, ast.UAdd, ast.USub, ast.Name, ast.Load, ast.Constant, ast.Call)
            for node in ast.walk(tree):
                if not isinstance(node, permitted):
                    raise ValueError("Unsupported mathematical operation")
                if isinstance(node, ast.Call) and (not isinstance(node.func, ast.Name)
                        or node.func.id not in functions or len(node.args) != 1 or node.keywords):
                    raise ValueError("Use a supported function with one argument")
        return self

    def update(self, payload: dict) -> bool:
        """Apply only bounded exploratory values; visuals never grade."""
        if not isinstance(payload, dict):
            return False
        if self.kind == "graph":
            values = payload.get("params")
            if not isinstance(values, dict) or set(values) != {p.name for p in self.params}:
                return False
            if any(isinstance(values[p.name], bool) or not isinstance(values[p.name], (float, int))
                   or not math.isfinite(values[p.name]) or not p.min <= values[p.name] <= p.max
                   for p in self.params):
                return False
            for param in self.params:
                param.initial = values[param.name]
            return True
        if self.kind in ("annotated_image", "process_flow", "timeline", "number_line",
                         "comparison", "sequence", "fraction_bar"):
            value = payload.get("value")
            limit = self.parts if self.kind == "fraction_bar" else len(self.entries) - 1
            if type(value) is not int or not 0 <= value <= limit:
                return False
            self.value = value
            return True
        return False


def visual_from_numbered_steps(title: str, board_content: str) -> TeachingVisual | None:
    """Conservative Classroom visual fallback built from existing numbered steps.

    The fallback reuses the teacher's own facts. It does not invent events,
    relationships, or media when the authored model omits an optional visual.
    Only explicitly ordered, consecutive steps qualify.
    """
    steps: list[str] = []
    for line in (board_content or "").splitlines():
        match = re.match(r"^\s*(\d+)[.)]\s+(.+?)\s*$", line)
        if not match:
            continue
        if int(match.group(1)) != len(steps) + 1:
            return None
        steps.append(match.group(2).strip())
    if len(steps) < 2 or len(steps) > 8 or any(len(x) < 5 for x in steps):
        return None
    return TeachingVisual(
        kind="process_flow",
        title=(title.strip() if title and len(title.strip()) >= 3 else "Steps in this process")[:100],
        caption="Follow these ordered steps to see how the process unfolds.",
        description=("Ordered steps: " + "; ".join(steps))[:600],
        entries=[VisualItem(label=f"Step {index}", detail=step[:240])
                 for index, step in enumerate(steps, start=1)],
    )


async def resolve_visual_media(visual: TeachingVisual) -> TeachingVisual:
    """Resolve an annotated-image query through a fixed, trusted endpoint.

    Failure is intentionally non-fatal: the clients render the visual's
    description and annotations without the photo rather than stalling class.
    """
    if visual.kind != "annotated_image":
        return visual

    query = visual.image_query.strip()
    if not query:
        return visual.model_copy(update={"image_url": None, "source_url": None, "attribution": None})

    cached = _IMAGE_CACHE.get(query.casefold())
    if cached:
        return visual.model_copy(update={
            "image_url": cached[0], "source_url": cached[1], "attribution": cached[2],
        })

    params = {
        "action": "query",
        "generator": "search",
        "gsrsearch": f"filetype:bitmap {query}",
        "gsrnamespace": "6",
        "gsrlimit": "1",
        "prop": "imageinfo|info",
        "inprop": "url",
        "iiprop": "url|extmetadata",
        "iiurlwidth": "1200",
        "format": "json",
        "origin": "*",
    }
    resolved: tuple[str, str, str] | None = None
    try:
        async with httpx.AsyncClient(
            timeout=2.5,
            follow_redirects=True,
            headers={"User-Agent": "LyoAI-Classroom/1.0 educational-visual-resolver"},
        ) as client:
            response = await client.get("https://commons.wikimedia.org/w/api.php", params=params)
            response.raise_for_status()
            pages = (response.json().get("query") or {}).get("pages") or {}
            page = next(iter(pages.values()), None)
            info = (page or {}).get("imageinfo") or []
            image = info[0] if info else {}
            image_url = image.get("thumburl") or image.get("url")
            source_url = (page or {}).get("canonicalurl")
            if not source_url and page and page.get("title"):
                from urllib.parse import quote
                source_url = "https://commons.wikimedia.org/wiki/" + quote(page["title"].replace(" ", "_"))
            metadata = image.get("extmetadata") or {}
            def plain_meta(name: str) -> str:
                raw = str((metadata.get(name) or {}).get("value") or "")
                raw = re.sub(r"<[^>]+>", " ", raw)
                return " ".join(html.unescape(raw).split())

            author = plain_meta("Artist") or plain_meta("Credit")
            license_name = plain_meta("LicenseShortName")
            title = (page or {}).get("title") or "Wikimedia Commons"
            attribution_parts = [part for part in (title, author, license_name) if part]
            attribution = " · ".join(dict.fromkeys(attribution_parts)) or "Wikimedia Commons"
            if _trusted_https(image_url) and _trusted_https(source_url):
                resolved = (image_url, source_url, attribution[:240])
    except Exception:
        resolved = None

    if resolved:
        # Cache successful trusted media, not transient upstream failures.
        # Concurrent failed lookups must never overwrite a successful one.
        if len(_IMAGE_CACHE) >= 128 and query.casefold() not in _IMAGE_CACHE:
            _IMAGE_CACHE.pop(next(iter(_IMAGE_CACHE)))
        _IMAGE_CACHE[query.casefold()] = resolved
    else:
        resolved = _IMAGE_CACHE.get(query.casefold())
    if not resolved:
        return visual.model_copy(update={"image_url": None, "source_url": None, "attribution": None})
    return visual.model_copy(update={
        "image_url": resolved[0], "source_url": resolved[1], "attribution": resolved[2],
    })


async def hydrate_turn_visuals(turn: Any) -> Any:
    """Resolve every visual in one learner-paced turn before it is persisted.

    Multiple demonstration beats are resolved concurrently so adding a real
    image does not multiply the post-generation wait by the number of beats.
    """
    beats = [turn, *getattr(turn, "demonstration", [])]
    targets = [(beat, getattr(beat, "visual", None)) for beat in beats]
    targets = [(beat, visual) for beat, visual in targets if visual is not None]
    if not targets:
        return turn
    resolved = await asyncio.gather(*(resolve_visual_media(visual) for _, visual in targets))
    for (beat, _), visual in zip(targets, resolved):
        beat.visual = visual
    return turn
