"""Add Canonical Skill Graph models

Revision ID: 8c022caccfda
Revises: 06351054f90b
Create Date: 2026-02-27 12:55:29.831804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8c022caccfda'
down_revision: Union[str, None] = '06351054f90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.Enum('ACADEMIC', 'CAPABILITY', 'LIFE', name='skilldomain'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_index(op.f('ix_skills_domain'), 'skills', ['domain'], unique=False)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('skill_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_skill_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_skill_id'], ['skills.id'], name=op.f('fk_skill_edges_prerequisite_skill_id_skills')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_edges_skill_id_skills')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_edges')),
    sa.UniqueConstraint('skill_id', 'prerequisite_skill_id', name='uq_skill_edge')
    )
    op.create_index(op.f('ix_skill_edges_id'), 'skill_edges', ['id'], unique=False)
    op.create_index(op.f('ix_skill_edges_prerequisite_skill_id'), 'skill_edges', ['prerequisite_skill_id'], unique=False)
    op.create_index(op.f('ix_skill_edges_skill_id'), 'skill_edges', ['skill_id'], unique=False)
    op.create_table('skill_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_tags_skill_id_skills')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_tags')),
    sa.UniqueConstraint('skill_id', 'tag', name='uq_skill_tag')
    )
    op.create_index(op.f('ix_skill_tags_id'), 'skill_tags', ['id'], unique=False)
    op.create_index(op.f('ix_skill_tags_skill_id'), 'skill_tags', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_tags_tag'), 'skill_tags', ['tag'], unique=False)
    op.drop_table('celebration_configs')
    op.drop_index(op.f('ix_course_progress_user_id'), table_name='course_progress')
    op.drop_index(op.f('ix_progress_user_course'), table_name='course_progress')
    op.drop_table('course_progress')
    op.drop_index(op.f('ix_user_soft_skills_id'), table_name='user_soft_skills')
    op.drop_index(op.f('ix_user_soft_skills_skill_name'), table_name='user_soft_skills')
    op.drop_index(op.f('ix_user_soft_skills_user_id'), table_name='user_soft_skills')
    op.drop_table('user_soft_skills')
    op.drop_index(op.f('ix_resource_tags_tag'), table_name='resource_tags')
    op.drop_table('resource_tags')
    op.drop_index(op.f('ix_mentor_conversations_id'), table_name='mentor_conversations')
    op.drop_index(op.f('ix_mentor_conversations_user_id'), table_name='mentor_conversations')
    op.drop_table('mentor_conversations')
    op.drop_index(op.f('ix_mastery_states_user_id'), table_name='mastery_states')
    op.drop_index(op.f('ix_mastery_user_concept'), table_name='mastery_states')
    op.drop_index(op.f('ix_mastery_user_objective'), table_name='mastery_states')
    op.drop_table('mastery_states')
    op.drop_index(op.f('ix_ambient_presence_states_organization_id'), table_name='ambient_presence_states')
    op.drop_index(op.f('ix_ambient_presence_states_user_id'), table_name='ambient_presence_states')
    op.drop_table('ambient_presence_states')
    op.drop_table('conversation_participants')
    op.drop_table('message_read_receipts')
    op.drop_table('resource_collections')
    op.drop_index(op.f('ix_chat_conversations_organization_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_session_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_user_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index(op.f('ix_review_active'), table_name='review_schedules')
    op.drop_index(op.f('ix_review_schedules_next_review_at'), table_name='review_schedules')
    op.drop_index(op.f('ix_review_schedules_user_id'), table_name='review_schedules')
    op.drop_index(op.f('ix_review_user_next'), table_name='review_schedules')
    op.drop_table('review_schedules')
    op.drop_index(op.f('ix_concepts_subject'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_mentor_messages_conversation_id'), table_name='mentor_messages')
    op.drop_index(op.f('ix_mentor_messages_id'), table_name='mentor_messages')
    op.drop_table('mentor_messages')
    op.drop_index(op.f('ix_chat_telemetry_created_at'), table_name='chat_telemetry')
    op.drop_index(op.f('ix_chat_telemetry_event_time'), table_name='chat_telemetry')
    op.drop_index(op.f('ix_chat_telemetry_event_type'), table_name='chat_telemetry')
    op.drop_index(op.f('ix_chat_telemetry_organization_id'), table_name='chat_telemetry')
    op.drop_index(op.f('ix_chat_telemetry_user_id'), table_name='chat_telemetry')
    op.drop_table('chat_telemetry')
    op.drop_index(op.f('ix_educational_resources_external_id'), table_name='educational_resources')
    op.drop_index(op.f('ix_educational_resources_id'), table_name='educational_resources')
    op.drop_index(op.f('ix_educational_resources_provider'), table_name='educational_resources')
    op.drop_index(op.f('ix_educational_resources_resource_type'), table_name='educational_resources')
    op.drop_index(op.f('ix_educational_resources_subject_area'), table_name='educational_resources')
    op.drop_index(op.f('ix_educational_resources_title'), table_name='educational_resources')
    op.drop_table('educational_resources')
    op.drop_index(op.f('ix_chat_messages_conv_created'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_organization_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_courses_created'), table_name='chat_courses')
    op.drop_index(op.f('ix_chat_courses_organization_id'), table_name='chat_courses')
    op.drop_index(op.f('ix_chat_courses_topic'), table_name='chat_courses')
    op.drop_index(op.f('ix_chat_courses_user_id'), table_name='chat_courses')
    op.drop_index(op.f('ix_chat_courses_user_topic'), table_name='chat_courses')
    op.drop_table('chat_courses')
    op.drop_table('course_resources')
    op.drop_table('story_views')
    op.drop_index(op.f('ix_course_generation_jobs_created_at'), table_name='course_generation_jobs')
    op.drop_index(op.f('ix_course_generation_jobs_status'), table_name='course_generation_jobs')
    op.drop_index(op.f('ix_course_generation_jobs_user_id'), table_name='course_generation_jobs')
    op.drop_table('course_generation_jobs')
    op.drop_index(op.f('ix_generated_courses_title'), table_name='generated_courses')
    op.drop_index(op.f('ix_generated_courses_topic'), table_name='generated_courses')
    op.drop_index(op.f('ix_generated_courses_user_id'), table_name='generated_courses')
    op.drop_table('generated_courses')
    op.drop_table('ad_placement_configs')
    op.drop_index(op.f('ix_file_assets_id'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_organization_id'), table_name='file_assets')
    op.drop_index(op.f('ix_file_assets_user_id'), table_name='file_assets')
    op.drop_table('file_assets')
    op.drop_index(op.f('ix_learning_edges_course_id'), table_name='learning_edges')
    op.drop_index(op.f('ix_learning_edges_from'), table_name='learning_edges')
    op.drop_index(op.f('ix_learning_edges_to'), table_name='learning_edges')
    op.drop_table('learning_edges')
    op.drop_index(op.f('ix_attempts_created'), table_name='interaction_attempts')
    op.drop_index(op.f('ix_attempts_user_node'), table_name='interaction_attempts')
    op.drop_index(op.f('ix_interaction_attempts_user_id'), table_name='interaction_attempts')
    op.drop_table('interaction_attempts')
    op.drop_index(op.f('ix_user_notification_preferences_organization_id'), table_name='user_notification_preferences')
    op.drop_index(op.f('ix_user_notification_preferences_user_id'), table_name='user_notification_preferences')
    op.drop_table('user_notification_preferences')
    op.drop_index(op.f('ix_graph_courses_subject'), table_name='graph_courses')
    op.drop_index(op.f('ix_graph_courses_subject_grade'), table_name='graph_courses')
    op.drop_table('graph_courses')
    op.drop_table('messages')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_mentor_suggestions_id'), table_name='mentor_suggestions')
    op.drop_index(op.f('ix_mentor_suggestions_user_id'), table_name='mentor_suggestions')
    op.drop_table('mentor_suggestions')
    op.drop_index(op.f('ix_struggle_predictions_content_id'), table_name='struggle_predictions')
    op.drop_index(op.f('ix_struggle_predictions_organization_id'), table_name='struggle_predictions')
    op.drop_index(op.f('ix_struggle_predictions_predicted_at'), table_name='struggle_predictions')
    op.drop_index(op.f('ix_struggle_predictions_user_id'), table_name='struggle_predictions')
    op.drop_table('struggle_predictions')
    op.drop_index(op.f('ix_learning_nodes_course_id'), table_name='learning_nodes')
    op.drop_index(op.f('ix_learning_nodes_course_sequence'), table_name='learning_nodes')
    op.drop_index(op.f('ix_learning_nodes_objective_id'), table_name='learning_nodes')
    op.drop_table('learning_nodes')
    op.drop_index(op.f('ix_inline_help_logs_organization_id'), table_name='inline_help_logs')
    op.drop_index(op.f('ix_inline_help_logs_user_id'), table_name='inline_help_logs')
    op.drop_table('inline_help_logs')
    op.drop_index(op.f('ix_proofs_of_learning_id'), table_name='proofs_of_learning')
    op.drop_index(op.f('ix_proofs_of_learning_proof_hash'), table_name='proofs_of_learning')
    op.drop_index(op.f('ix_proofs_of_learning_user_id'), table_name='proofs_of_learning')
    op.drop_table('proofs_of_learning')
    op.drop_index(op.f('ix_intervention_logs_intervention_type'), table_name='intervention_logs')
    op.drop_index(op.f('ix_intervention_logs_organization_id'), table_name='intervention_logs')
    op.drop_index(op.f('ix_intervention_logs_triggered_at'), table_name='intervention_logs')
    op.drop_index(op.f('ix_intervention_logs_user_id'), table_name='intervention_logs')
    op.drop_table('intervention_logs')
    op.drop_index(op.f('ix_mentor_actions_conversation_id'), table_name='mentor_actions')
    op.drop_index(op.f('ix_mentor_actions_id'), table_name='mentor_actions')
    op.drop_index(op.f('ix_mentor_actions_user_id'), table_name='mentor_actions')
    op.drop_table('mentor_actions')
    op.drop_index(op.f('ix_chat_notes_created'), table_name='chat_notes')
    op.drop_index(op.f('ix_chat_notes_organization_id'), table_name='chat_notes')
    op.drop_index(op.f('ix_chat_notes_topic'), table_name='chat_notes')
    op.drop_index(op.f('ix_chat_notes_user_id'), table_name='chat_notes')
    op.drop_index(op.f('ix_chat_notes_user_topic'), table_name='chat_notes')
    op.drop_table('chat_notes')
    op.drop_index(op.f('ix_misconceptions_concept_id'), table_name='misconceptions')
    op.drop_table('misconceptions')
    op.drop_table('stories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('media_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('text_content', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('story_metadata', sqlite.JSON(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('is_highlight', sa.BOOLEAN(), nullable=True),
    sa.Column('view_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories'))
    )
    op.create_table('misconceptions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('concept_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('label', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('example_wrong_beliefs', sqlite.JSON(), nullable=True),
    sa.Column('remediation_strategy', sa.TEXT(), nullable=True),
    sa.Column('suggested_analogy', sa.TEXT(), nullable=True),
    sa.Column('occurrence_count', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_misconceptions_concept_id_concepts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_misconceptions'))
    )
    op.create_index(op.f('ix_misconceptions_concept_id'), 'misconceptions', ['concept_id'], unique=False)
    op.create_table('chat_notes',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('topic', sa.VARCHAR(length=200), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('source_message_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('source_conversation_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('related_course_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('note_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('importance', sa.INTEGER(), nullable=False),
    sa.Column('is_archived', sa.BOOLEAN(), nullable=False),
    sa.Column('is_favorite', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_chat_notes_organization_id_organizations')),
    sa.ForeignKeyConstraint(['related_course_id'], ['chat_courses.id'], name=op.f('fk_chat_notes_related_course_id_chat_courses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_notes'))
    )
    op.create_index(op.f('ix_chat_notes_user_topic'), 'chat_notes', ['user_id', 'topic'], unique=False)
    op.create_index(op.f('ix_chat_notes_user_id'), 'chat_notes', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_notes_topic'), 'chat_notes', ['topic'], unique=False)
    op.create_index(op.f('ix_chat_notes_organization_id'), 'chat_notes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_chat_notes_created'), 'chat_notes', ['created_at'], unique=False)
    op.create_table('mentor_actions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('content_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('action_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['mentor_conversations.id'], name=op.f('fk_mentor_actions_conversation_id_mentor_conversations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mentor_actions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentor_actions'))
    )
    op.create_index(op.f('ix_mentor_actions_user_id'), 'mentor_actions', ['user_id'], unique=False)
    op.create_index(op.f('ix_mentor_actions_id'), 'mentor_actions', ['id'], unique=False)
    op.create_index(op.f('ix_mentor_actions_conversation_id'), 'mentor_actions', ['conversation_id'], unique=False)
    op.create_table('intervention_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('intervention_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('triggered_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('delivered_at', sa.DATETIME(), nullable=True),
    sa.Column('user_response', sa.VARCHAR(length=50), nullable=True),
    sa.Column('response_at', sa.DATETIME(), nullable=True),
    sa.Column('context', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_intervention_logs_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intervention_logs'))
    )
    op.create_index(op.f('ix_intervention_logs_user_id'), 'intervention_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_intervention_logs_triggered_at'), 'intervention_logs', ['triggered_at'], unique=False)
    op.create_index(op.f('ix_intervention_logs_organization_id'), 'intervention_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_intervention_logs_intervention_type'), 'intervention_logs', ['intervention_type'], unique=False)
    op.create_table('proofs_of_learning',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('course_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('issued_at', sa.DATETIME(), nullable=True),
    sa.Column('proof_hash', sa.VARCHAR(), nullable=True),
    sa.Column('skills_validated', sqlite.JSON(), nullable=True),
    sa.Column('issuer', sa.VARCHAR(), nullable=True),
    sa.Column('verification_url', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_proofs_of_learning_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proofs_of_learning'))
    )
    op.create_index(op.f('ix_proofs_of_learning_user_id'), 'proofs_of_learning', ['user_id'], unique=False)
    op.create_index(op.f('ix_proofs_of_learning_proof_hash'), 'proofs_of_learning', ['proof_hash'], unique=1)
    op.create_index(op.f('ix_proofs_of_learning_id'), 'proofs_of_learning', ['id'], unique=False)
    op.create_table('inline_help_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('help_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('help_text', sa.VARCHAR(length=500), nullable=False),
    sa.Column('page', sa.VARCHAR(length=100), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), nullable=True),
    sa.Column('content_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_response', sa.VARCHAR(length=20), nullable=True),
    sa.Column('response_at', sa.DATETIME(), nullable=True),
    sa.Column('shown_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_inline_help_logs_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inline_help_logs'))
    )
    op.create_index(op.f('ix_inline_help_logs_user_id'), 'inline_help_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_inline_help_logs_organization_id'), 'inline_help_logs', ['organization_id'], unique=False)
    op.create_table('learning_nodes',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('node_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('content', sqlite.JSON(), nullable=False),
    sa.Column('objective_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('concept_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('prerequisites', sqlite.JSON(), nullable=True),
    sa.Column('estimated_seconds', sa.INTEGER(), nullable=False),
    sa.Column('asset_tier', sa.VARCHAR(length=20), nullable=False),
    sa.Column('generated_asset_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('generated_audio_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('interaction_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('skill_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('misconception_tags', sqlite.JSON(), nullable=True),
    sa.Column('remediation_budget', sa.INTEGER(), nullable=False),
    sa.Column('fallback_node_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('sequence_order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_learning_nodes_concept_id_concepts')),
    sa.ForeignKeyConstraint(['course_id'], ['graph_courses.id'], name=op.f('fk_learning_nodes_course_id_graph_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_nodes'))
    )
    op.create_index(op.f('ix_learning_nodes_objective_id'), 'learning_nodes', ['objective_id'], unique=False)
    op.create_index(op.f('ix_learning_nodes_course_sequence'), 'learning_nodes', ['course_id', 'sequence_order'], unique=False)
    op.create_index(op.f('ix_learning_nodes_course_id'), 'learning_nodes', ['course_id'], unique=False)
    op.create_table('struggle_predictions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('content_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('struggle_probability', sa.FLOAT(), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('prereq_mastery', sa.FLOAT(), nullable=True),
    sa.Column('similar_performance', sa.FLOAT(), nullable=True),
    sa.Column('content_difficulty', sa.FLOAT(), nullable=True),
    sa.Column('days_since_review', sa.INTEGER(), nullable=True),
    sa.Column('cognitive_load', sa.FLOAT(), nullable=True),
    sa.Column('sentiment_trend', sa.FLOAT(), nullable=True),
    sa.Column('prediction_features', sqlite.JSON(), nullable=True),
    sa.Column('actual_struggled', sa.BOOLEAN(), nullable=True),
    sa.Column('actual_outcome_at', sa.DATETIME(), nullable=True),
    sa.Column('intervention_offered', sa.BOOLEAN(), nullable=False),
    sa.Column('intervention_accepted', sa.BOOLEAN(), nullable=True),
    sa.Column('predicted_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_struggle_predictions_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_struggle_predictions'))
    )
    op.create_index(op.f('ix_struggle_predictions_user_id'), 'struggle_predictions', ['user_id'], unique=False)
    op.create_index(op.f('ix_struggle_predictions_predicted_at'), 'struggle_predictions', ['predicted_at'], unique=False)
    op.create_index(op.f('ix_struggle_predictions_organization_id'), 'struggle_predictions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_struggle_predictions_content_id'), 'struggle_predictions', ['content_id'], unique=False)
    op.create_table('mentor_suggestions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('suggestion_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('content_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('suggestion_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('acted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mentor_suggestions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentor_suggestions'))
    )
    op.create_index(op.f('ix_mentor_suggestions_user_id'), 'mentor_suggestions', ['user_id'], unique=False)
    op.create_index(op.f('ix_mentor_suggestions_id'), 'mentor_suggestions', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('message_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('media_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('message_metadata', sqlite.JSON(), nullable=True),
    sa.Column('is_edited', sa.BOOLEAN(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_table('graph_courses',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=100), nullable=False),
    sa.Column('grade_band', sa.VARCHAR(length=50), nullable=True),
    sa.Column('visual_theme', sa.VARCHAR(length=50), nullable=False),
    sa.Column('audio_mood', sa.VARCHAR(length=50), nullable=False),
    sa.Column('entry_node_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('estimated_minutes', sa.INTEGER(), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=50), nullable=False),
    sa.Column('learning_objectives', sqlite.JSON(), nullable=True),
    sa.Column('prerequisites', sqlite.JSON(), nullable=True),
    sa.Column('source_intent', sa.TEXT(), nullable=True),
    sa.Column('source_conversation_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.Column('is_template', sa.BOOLEAN(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_courses'))
    )
    op.create_index(op.f('ix_graph_courses_subject_grade'), 'graph_courses', ['subject', 'grade_band'], unique=False)
    op.create_index(op.f('ix_graph_courses_subject'), 'graph_courses', ['subject'], unique=False)
    op.create_table('user_notification_preferences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('dnd_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('quiet_hours_start', sa.TIME(), nullable=True),
    sa.Column('quiet_hours_end', sa.TIME(), nullable=True),
    sa.Column('max_notifications_per_day', sa.INTEGER(), nullable=False),
    sa.Column('enabled_intervention_types', sqlite.JSON(), nullable=True),
    sa.Column('disabled_intervention_types', sqlite.JSON(), nullable=True),
    sa.Column('preferred_study_times', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_user_notification_preferences_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_notification_preferences'))
    )
    op.create_index(op.f('ix_user_notification_preferences_user_id'), 'user_notification_preferences', ['user_id'], unique=1)
    op.create_index(op.f('ix_user_notification_preferences_organization_id'), 'user_notification_preferences', ['organization_id'], unique=False)
    op.create_table('interaction_attempts',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('node_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_answer', sa.TEXT(), nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=False),
    sa.Column('time_taken_seconds', sa.FLOAT(), nullable=True),
    sa.Column('attempt_number', sa.INTEGER(), nullable=False),
    sa.Column('remediation_shown', sa.BOOLEAN(), nullable=False),
    sa.Column('detected_misconception_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['detected_misconception_id'], ['misconceptions.id'], name=op.f('fk_interaction_attempts_detected_misconception_id_misconceptions')),
    sa.ForeignKeyConstraint(['node_id'], ['learning_nodes.id'], name=op.f('fk_interaction_attempts_node_id_learning_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interaction_attempts'))
    )
    op.create_index(op.f('ix_interaction_attempts_user_id'), 'interaction_attempts', ['user_id'], unique=False)
    op.create_index(op.f('ix_attempts_user_node'), 'interaction_attempts', ['user_id', 'node_id'], unique=False)
    op.create_index(op.f('ix_attempts_created'), 'interaction_attempts', ['created_at'], unique=False)
    op.create_table('learning_edges',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('from_node_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('to_node_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('condition', sa.VARCHAR(length=50), nullable=False),
    sa.Column('mastery_threshold', sa.FLOAT(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['graph_courses.id'], name=op.f('fk_learning_edges_course_id_graph_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_node_id'], ['learning_nodes.id'], name=op.f('fk_learning_edges_from_node_id_learning_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['learning_nodes.id'], name=op.f('fk_learning_edges_to_node_id_learning_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_edges')),
    sa.UniqueConstraint('from_node_id', 'to_node_id', 'condition', name=op.f('uq_edge_connection'))
    )
    op.create_index(op.f('ix_learning_edges_to'), 'learning_edges', ['to_node_id'], unique=False)
    op.create_index(op.f('ix_learning_edges_from'), 'learning_edges', ['from_node_id'], unique=False)
    op.create_index(op.f('ix_learning_edges_course_id'), 'learning_edges', ['course_id'], unique=False)
    op.create_table('file_assets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('url', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('size_bytes', sa.INTEGER(), nullable=False),
    sa.Column('is_private', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_file_assets_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_file_assets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_assets')),
    sa.UniqueConstraint('file_path', name=op.f('uq_file_assets_file_path'))
    )
    op.create_index(op.f('ix_file_assets_user_id'), 'file_assets', ['user_id'], unique=False)
    op.create_index(op.f('ix_file_assets_organization_id'), 'file_assets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_file_assets_id'), 'file_assets', ['id'], unique=False)
    op.create_table('ad_placement_configs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('placement_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('min_latency_ms', sa.INTEGER(), nullable=False),
    sa.Column('max_frequency_per_session', sa.INTEGER(), nullable=False),
    sa.Column('cooldown_seconds', sa.INTEGER(), nullable=False),
    sa.Column('ad_unit_id', sa.VARCHAR(length=200), nullable=False),
    sa.Column('ad_format', sa.VARCHAR(length=50), nullable=False),
    sa.Column('target_subjects', sqlite.JSON(), nullable=True),
    sa.Column('exclude_premium', sa.BOOLEAN(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_placement_configs'))
    )
    op.create_table('generated_courses',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('job_id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('topic', sa.VARCHAR(length=200), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=20), nullable=False),
    sa.Column('duration_hours', sa.FLOAT(), nullable=False),
    sa.Column('course_data', sqlite.JSON(), nullable=False),
    sa.Column('quality_score', sa.FLOAT(), nullable=True),
    sa.Column('is_approved', sa.BOOLEAN(), nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('view_count', sa.INTEGER(), nullable=True),
    sa.Column('enrollment_count', sa.INTEGER(), nullable=True),
    sa.Column('completion_count', sa.INTEGER(), nullable=True),
    sa.Column('average_rating', sa.FLOAT(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('parent_course_id', sa.CHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['course_generation_jobs.id'], name=op.f('fk_generated_courses_job_id_course_generation_jobs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_generated_courses_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_courses'))
    )
    op.create_index(op.f('ix_generated_courses_user_id'), 'generated_courses', ['user_id'], unique=False)
    op.create_index(op.f('ix_generated_courses_topic'), 'generated_courses', ['topic'], unique=False)
    op.create_index(op.f('ix_generated_courses_title'), 'generated_courses', ['title'], unique=False)
    op.create_table('course_generation_jobs',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=17), nullable=True),
    sa.Column('current_step', sa.VARCHAR(length=50), nullable=True),
    sa.Column('progress_percent', sa.INTEGER(), nullable=True),
    sa.Column('user_prompt', sa.TEXT(), nullable=False),
    sa.Column('user_preferences', sqlite.JSON(), nullable=True),
    sa.Column('intent_result', sqlite.JSON(), nullable=True),
    sa.Column('curriculum_result', sqlite.JSON(), nullable=True),
    sa.Column('content_results', sqlite.JSON(), nullable=True),
    sa.Column('assessment_result', sqlite.JSON(), nullable=True),
    sa.Column('qa_result', sqlite.JSON(), nullable=True),
    sa.Column('final_course', sqlite.JSON(), nullable=True),
    sa.Column('final_course_id', sa.CHAR(length=32), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('error_step', sa.VARCHAR(length=50), nullable=True),
    sa.Column('retry_count', sa.INTEGER(), nullable=True),
    sa.Column('max_retries', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('last_updated_at', sa.DATETIME(), nullable=True),
    sa.Column('total_tokens_used', sa.INTEGER(), nullable=True),
    sa.Column('generation_time_seconds', sa.FLOAT(), nullable=True),
    sa.Column('estimated_cost_usd', sa.FLOAT(), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('is_premium', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_course_generation_jobs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_generation_jobs'))
    )
    op.create_index(op.f('ix_course_generation_jobs_user_id'), 'course_generation_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_course_generation_jobs_status'), 'course_generation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_course_generation_jobs_created_at'), 'course_generation_jobs', ['created_at'], unique=False)
    op.create_table('story_views',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('story_id', sa.INTEGER(), nullable=False),
    sa.Column('viewer_id', sa.INTEGER(), nullable=False),
    sa.Column('viewed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_views_story_id_stories')),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], name=op.f('fk_story_views_viewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_views'))
    )
    op.create_table('course_resources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.Column('resource_id', sa.INTEGER(), nullable=True),
    sa.Column('resource_order', sa.INTEGER(), nullable=True),
    sa.Column('is_required', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_resources_course_id_courses')),
    sa.ForeignKeyConstraint(['resource_id'], ['educational_resources.id'], name=op.f('fk_course_resources_resource_id_educational_resources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_resources'))
    )
    op.create_table('chat_courses',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('topic', sa.VARCHAR(length=200), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=50), nullable=False),
    sa.Column('modules', sqlite.JSON(), nullable=True),
    sa.Column('learning_objectives', sqlite.JSON(), nullable=True),
    sa.Column('prerequisites', sqlite.JSON(), nullable=True),
    sa.Column('estimated_hours', sa.FLOAT(), nullable=True),
    sa.Column('generated_by_mode', sa.VARCHAR(length=50), nullable=False),
    sa.Column('source_conversation_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_chat_courses_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_courses'))
    )
    op.create_index(op.f('ix_chat_courses_user_topic'), 'chat_courses', ['user_id', 'topic'], unique=False)
    op.create_index(op.f('ix_chat_courses_user_id'), 'chat_courses', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_courses_topic'), 'chat_courses', ['topic'], unique=False)
    op.create_index(op.f('ix_chat_courses_organization_id'), 'chat_courses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_chat_courses_created'), 'chat_courses', ['created_at'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('conversation_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('mode_used', sa.VARCHAR(length=50), nullable=False),
    sa.Column('action_triggered', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), nullable=True),
    sa.Column('model_used', sa.VARCHAR(length=100), nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), nullable=True),
    sa.Column('ctas', sqlite.JSON(), nullable=True),
    sa.Column('chip_actions', sqlite.JSON(), nullable=True),
    sa.Column('cache_hit', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], name=op.f('fk_chat_messages_conversation_id_chat_conversations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_chat_messages_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_organization_id'), 'chat_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_conv_created'), 'chat_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('educational_resources',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('author', sa.VARCHAR(length=200), nullable=True),
    sa.Column('publisher', sa.VARCHAR(length=200), nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=8), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=17), nullable=False),
    sa.Column('subject_area', sa.VARCHAR(length=100), nullable=True),
    sa.Column('difficulty_level', sa.VARCHAR(length=50), nullable=True),
    sa.Column('external_id', sa.VARCHAR(length=200), nullable=True),
    sa.Column('external_url', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('thumbnail_url', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('download_url', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), nullable=True),
    sa.Column('page_count', sa.INTEGER(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), nullable=True),
    sa.Column('isbn', sa.VARCHAR(length=20), nullable=True),
    sa.Column('quality_score', sa.INTEGER(), nullable=True),
    sa.Column('is_curated', sa.BOOLEAN(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('raw_api_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('last_verified', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_educational_resources'))
    )
    op.create_index(op.f('ix_educational_resources_title'), 'educational_resources', ['title'], unique=False)
    op.create_index(op.f('ix_educational_resources_subject_area'), 'educational_resources', ['subject_area'], unique=False)
    op.create_index(op.f('ix_educational_resources_resource_type'), 'educational_resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_educational_resources_provider'), 'educational_resources', ['provider'], unique=False)
    op.create_index(op.f('ix_educational_resources_id'), 'educational_resources', ['id'], unique=False)
    op.create_index(op.f('ix_educational_resources_external_id'), 'educational_resources', ['external_id'], unique=False)
    op.create_table('chat_telemetry',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('conversation_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('message_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('mode_chosen', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), nullable=True),
    sa.Column('cache_hit', sa.BOOLEAN(), nullable=False),
    sa.Column('cta_clicked', sa.VARCHAR(length=100), nullable=True),
    sa.Column('chip_action_used', sa.VARCHAR(length=50), nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), nullable=True),
    sa.Column('extra_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_chat_telemetry_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_telemetry'))
    )
    op.create_index(op.f('ix_chat_telemetry_user_id'), 'chat_telemetry', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_telemetry_organization_id'), 'chat_telemetry', ['organization_id'], unique=False)
    op.create_index(op.f('ix_chat_telemetry_event_type'), 'chat_telemetry', ['event_type'], unique=False)
    op.create_index(op.f('ix_chat_telemetry_event_time'), 'chat_telemetry', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_telemetry_created_at'), 'chat_telemetry', ['created_at'], unique=False)
    op.create_table('mentor_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('msg_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['mentor_conversations.id'], name=op.f('fk_mentor_messages_conversation_id_mentor_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentor_messages'))
    )
    op.create_index(op.f('ix_mentor_messages_id'), 'mentor_messages', ['id'], unique=False)
    op.create_index(op.f('ix_mentor_messages_conversation_id'), 'mentor_messages', ['conversation_id'], unique=False)
    op.create_table('concepts',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=100), nullable=False),
    sa.Column('grade_band', sa.VARCHAR(length=50), nullable=True),
    sa.Column('parent_concept_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_concept_id'], ['concepts.id'], name=op.f('fk_concepts_parent_concept_id_concepts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_concepts')),
    sa.UniqueConstraint('name', 'subject', name=op.f('uq_concept_name_subject'))
    )
    op.create_index(op.f('ix_concepts_subject'), 'concepts', ['subject', 'grade_band'], unique=False)
    op.create_table('review_schedules',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('node_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('concept_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('easiness_factor', sa.FLOAT(), nullable=False),
    sa.Column('interval_days', sa.INTEGER(), nullable=False),
    sa.Column('repetition_number', sa.INTEGER(), nullable=False),
    sa.Column('next_review_at', sa.DATETIME(), nullable=False),
    sa.Column('last_reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('last_quality', sa.INTEGER(), nullable=False),
    sa.Column('streak', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_review_schedules_concept_id_concepts')),
    sa.ForeignKeyConstraint(['node_id'], ['learning_nodes.id'], name=op.f('fk_review_schedules_node_id_learning_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_schedules'))
    )
    op.create_index(op.f('ix_review_user_next'), 'review_schedules', ['user_id', 'next_review_at'], unique=False)
    op.create_index(op.f('ix_review_schedules_user_id'), 'review_schedules', ['user_id'], unique=False)
    op.create_index(op.f('ix_review_schedules_next_review_at'), 'review_schedules', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_review_active'), 'review_schedules', ['user_id', 'is_active'], unique=False)
    op.create_table('chat_conversations',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('initial_mode', sa.VARCHAR(length=50), nullable=False),
    sa.Column('current_mode', sa.VARCHAR(length=50), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), nullable=True),
    sa.Column('message_count', sa.INTEGER(), nullable=False),
    sa.Column('last_message_at', sa.DATETIME(), nullable=True),
    sa.Column('context_data', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_chat_conversations_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_conversations'))
    )
    op.create_index(op.f('ix_chat_conversations_user_id'), 'chat_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_session_id'), 'chat_conversations', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_organization_id'), 'chat_conversations', ['organization_id'], unique=False)
    op.create_table('resource_collections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_collections'))
    )
    op.create_table('message_read_receipts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('read_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_read_receipts_message_id_messages')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_message_read_receipts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_read_receipts'))
    )
    op.create_table('conversation_participants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('joined_at', sa.DATETIME(), nullable=True),
    sa.Column('last_read_at', sa.DATETIME(), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_participants_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_participants_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_participants'))
    )
    op.create_table('ambient_presence_states',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('last_seen_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('current_page', sa.VARCHAR(length=100), nullable=True),
    sa.Column('current_topic', sa.VARCHAR(length=200), nullable=True),
    sa.Column('current_content_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('time_on_page', sa.FLOAT(), nullable=True),
    sa.Column('scroll_count', sa.INTEGER(), nullable=False),
    sa.Column('mouse_hesitations', sa.INTEGER(), nullable=False),
    sa.Column('inline_help_count_today', sa.INTEGER(), nullable=False),
    sa.Column('quick_access_count_today', sa.INTEGER(), nullable=False),
    sa.Column('context', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ambient_presence_states_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ambient_presence_states'))
    )
    op.create_index(op.f('ix_ambient_presence_states_user_id'), 'ambient_presence_states', ['user_id'], unique=False)
    op.create_index(op.f('ix_ambient_presence_states_organization_id'), 'ambient_presence_states', ['organization_id'], unique=False)
    op.create_table('mastery_states',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('concept_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('objective_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('mastery_score', sa.FLOAT(), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('attempts', sa.INTEGER(), nullable=False),
    sa.Column('correct_count', sa.INTEGER(), nullable=False),
    sa.Column('incorrect_count', sa.INTEGER(), nullable=False),
    sa.Column('error_pattern', sa.VARCHAR(length=200), nullable=True),
    sa.Column('misconception_tags', sqlite.JSON(), nullable=True),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.Column('last_correct', sa.DATETIME(), nullable=True),
    sa.Column('trend', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], name=op.f('fk_mastery_states_concept_id_concepts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mastery_states')),
    sa.UniqueConstraint('user_id', 'concept_id', name=op.f('uq_user_concept_mastery'))
    )
    op.create_index(op.f('ix_mastery_user_objective'), 'mastery_states', ['user_id', 'objective_id'], unique=False)
    op.create_index(op.f('ix_mastery_user_concept'), 'mastery_states', ['user_id', 'concept_id'], unique=False)
    op.create_index(op.f('ix_mastery_states_user_id'), 'mastery_states', ['user_id'], unique=False)
    op.create_table('mentor_conversations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('topic', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('context', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mentor_conversations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentor_conversations'))
    )
    op.create_index(op.f('ix_mentor_conversations_user_id'), 'mentor_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_mentor_conversations_id'), 'mentor_conversations', ['id'], unique=False)
    op.create_table('resource_tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resource_id', sa.INTEGER(), nullable=True),
    sa.Column('tag', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['educational_resources.id'], name=op.f('fk_resource_tags_resource_id_educational_resources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_tags'))
    )
    op.create_index(op.f('ix_resource_tags_tag'), 'resource_tags', ['tag'], unique=False)
    op.create_table('user_soft_skills',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('skill_name', sa.VARCHAR(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('evidence_count', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('recent_evidence', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_soft_skills_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_soft_skills'))
    )
    op.create_index(op.f('ix_user_soft_skills_user_id'), 'user_soft_skills', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_soft_skills_skill_name'), 'user_soft_skills', ['skill_name'], unique=False)
    op.create_index(op.f('ix_user_soft_skills_id'), 'user_soft_skills', ['id'], unique=False)
    op.create_table('course_progress',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('current_node_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('completed_node_ids', sqlite.JSON(), nullable=False),
    sa.Column('total_time_seconds', sa.INTEGER(), nullable=False),
    sa.Column('interactions_completed', sa.INTEGER(), nullable=False),
    sa.Column('interactions_passed', sa.INTEGER(), nullable=False),
    sa.Column('remediations_triggered', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('completion_percentage', sa.FLOAT(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_active_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['graph_courses.id'], name=op.f('fk_course_progress_course_id_graph_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_progress')),
    sa.UniqueConstraint('user_id', 'course_id', name=op.f('uq_user_course_progress'))
    )
    op.create_index(op.f('ix_progress_user_course'), 'course_progress', ['user_id', 'course_id'], unique=False)
    op.create_index(op.f('ix_course_progress_user_id'), 'course_progress', ['user_id'], unique=False)
    op.create_table('celebration_configs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('min_streak', sa.INTEGER(), nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('animation_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('sound_effect', sa.VARCHAR(length=100), nullable=True),
    sa.Column('message_template', sa.VARCHAR(length=500), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_celebration_configs'))
    )
    op.drop_index(op.f('ix_skill_tags_tag'), table_name='skill_tags')
    op.drop_index(op.f('ix_skill_tags_skill_id'), table_name='skill_tags')
    op.drop_index(op.f('ix_skill_tags_id'), table_name='skill_tags')
    op.drop_table('skill_tags')
    op.drop_index(op.f('ix_skill_edges_skill_id'), table_name='skill_edges')
    op.drop_index(op.f('ix_skill_edges_prerequisite_skill_id'), table_name='skill_edges')
    op.drop_index(op.f('ix_skill_edges_id'), table_name='skill_edges')
    op.drop_table('skill_edges')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_domain'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
