"""Add LearningEvents log models

Revision ID: facf1e28b4e6
Revises: 8c022caccfda
Create Date: 2026-02-27 13:00:33.785644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'facf1e28b4e6'
down_revision: Union[str, None] = '8c022caccfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('QUIZ_ANSWER', 'LESSON_COMPLETION', 'AI_SESSION', 'REFLECTION', 'PROJECT', name='eventtype'), nullable=False),
    sa.Column('skill_ids_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('measurable_outcome', sa.Float(), nullable=True),
    sa.Column('processed_for_mastery', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_events'))
    )
    op.create_index(op.f('ix_learning_events_event_type'), 'learning_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_learning_events_id'), 'learning_events', ['id'], unique=False)
    op.create_index(op.f('ix_learning_events_timestamp'), 'learning_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_learning_events_user_id'), 'learning_events', ['user_id'], unique=False)
    op.create_table('user_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ACHIEVED', 'DROPPED', name='goalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_goals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_goals'))
    )
    op.create_index(op.f('ix_user_goals_id'), 'user_goals', ['id'], unique=False)
    op.create_index(op.f('ix_user_goals_status'), 'user_goals', ['status'], unique=False)
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=False)
    op.create_table('goal_progress_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('overall_completion_percentage', sa.Float(), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['user_goals.id'], name=op.f('fk_goal_progress_snapshots_goal_id_user_goals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_progress_snapshots'))
    )
    op.create_index(op.f('ix_goal_progress_snapshots_goal_id'), 'goal_progress_snapshots', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_progress_snapshots_id'), 'goal_progress_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_goal_progress_snapshots_recorded_at'), 'goal_progress_snapshots', ['recorded_at'], unique=False)
    op.create_table('goal_skill_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('importance_weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['user_goals.id'], name=op.f('fk_goal_skill_mappings_goal_id_user_goals')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_goal_skill_mappings_skill_id_skills')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_skill_mappings')),
    sa.UniqueConstraint('goal_id', 'skill_id', name='uq_goal_skill_mapping')
    )
    op.create_index(op.f('ix_goal_skill_mappings_goal_id'), 'goal_skill_mappings', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_skill_mappings_id'), 'goal_skill_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_goal_skill_mappings_skill_id'), 'goal_skill_mappings', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_skill_mappings_skill_id'), table_name='goal_skill_mappings')
    op.drop_index(op.f('ix_goal_skill_mappings_id'), table_name='goal_skill_mappings')
    op.drop_index(op.f('ix_goal_skill_mappings_goal_id'), table_name='goal_skill_mappings')
    op.drop_table('goal_skill_mappings')
    op.drop_index(op.f('ix_goal_progress_snapshots_recorded_at'), table_name='goal_progress_snapshots')
    op.drop_index(op.f('ix_goal_progress_snapshots_id'), table_name='goal_progress_snapshots')
    op.drop_index(op.f('ix_goal_progress_snapshots_goal_id'), table_name='goal_progress_snapshots')
    op.drop_table('goal_progress_snapshots')
    op.drop_index(op.f('ix_user_goals_user_id'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_status'), table_name='user_goals')
    op.drop_index(op.f('ix_user_goals_id'), table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_learning_events_user_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_timestamp'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_id'), table_name='learning_events')
    op.drop_index(op.f('ix_learning_events_event_type'), table_name='learning_events')
    op.drop_table('learning_events')
    # ### end Alembic commands ###
